### ISSUE TITLE
User Question - "msg.payload needs to be a string."

### ISSUE THREAD

**Issue by quorn23** [Mar10-9us/node-red-contrib-discord-js#3]
Hi, 

Hope is alright if i bother you with an user question, hopefully it's very simple and just a mistake by a node-red newbie.

I'm using your addition in a Node-Red installation for Home Assistant.
When i use a "change" to change msg.payload to a string it works fine, the bot posts the message in the channel, this works also with for example a randomizer simply posting a number. So far so good. 

As Discord embed messages are json i add a "change" with msg.payload > JSON.

Json Example:
`{
    "content": "Content",
    "embeds": [
        {
            "color": 8947848,
            "fields": [
                {
                    "name": "Test​",
                    "value": "***Message:***"
                },
                {
                    "name": "Message",
                    "value": "Test​"
                }
            ],
            "author": {
                "name": "Gabe",
                "icon_url": "https://mydomain.com/icons/synology.png"
            },
            "footer": {
                "text": "Made by Gabe"
            }
        }
    ],
    "username": "Gabe",
    "avatar_url": "https://https://mydomain.com/icons/synology.png"
}`

Edit: As Github seems to break the json at least visually [here as pastebin](https://pastebin.com/0Sb2uSmY)

This results in the sendsimpleMessage node throwing me the error "msg.payload needs to be a string."

Where i'm stuck now, shouldn't the node accept a json payload for embed messages? If it needs to be a string, how would i need to format the payload to be accepted and send as embed message?

Thanks in advance!

**Comment by Mar10-9us** [comment]
Hi, @quorn23 !

This is not an issue caused by you being a node-red newbie, but rather that the node not itself does not supports embeds - hence the name send**SIMPLE**Message.

The next update, which im planning on releasing this weekend or by next week, will contain an 'sendAdvancedMessage'-node, which will support embeds.

Thanks for using my node and providing feedback! This is my first ever javascript and node-project!

Joe

**Comment by quorn23** [comment]
Hi Joe,

Thanks for the feedback, after looking into discord js docs i got the feeling, i'm trying to do something, that's not simply done by feeding it a json payload. Glad to hear it's not me starting with node-red and more me not understanding discord js on a level, that would avoid such a question ;)

That's great to hear, no rush on my side, i still got plenty to explore until the update. 
As in feedback, in case the syntax for adding an embed message could be a tad confusing, me and probably others wouldn't mind if you add an example to the read-me. 

I'll close the issue, as it's basically a feature request of a feature you're already working on.

Cheers,
Gabe
